baseURL = "https://torapon-kenkou.com/"
languageCode = "ja"
title = "健康の窓口"
theme = "PaperMod"

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = false

  [params.profileMode]
    enabled = true
    title = "Toraponの健康ブログ"
    subtitle = "認知症・介護・健康について、わかりやすい情報をお届けします。"
    imageUrl = "/images/tiger.png"
    imageWidth = 280
    imageHeight = 280
    imageTitle = "Torapon"

  [params.cover]
    hiddenInList = false
    hiddenInSingle = false

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/Torapon0104"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[[menus.main]]
  name = "記事一覧"
  url = "/posts/"
  weight = 10

[[menus.main]]
  name = "プロフィール"
  url = "/posts/pages/2023/profile/"
  weight = 20

[[menus.main]]
  name = "サイトマップ"
  url = "/posts/pages/2023/sitemap/"
  weight = 30

[[menus.main]]
  name = "プライバシーポリシー"
  url = "/posts/pages/2023/privacypolicy/"
  weight = 35

[[menus.main]]
  name = "お問い合わせ"
  url = "/posts/pages/2023/contact/"
  weight = 40

[[menus.main]]
  name = "姉妹サイト：ゴルフのカラダ研究所"
  url = "https://golf-karada.com/"
  weight = 50
