baseURL = "/"
languageCode = "ja"
title = "健康の窓口〜おっちゃんに言わせて"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
